# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2daa96c4ca95a16017dea39452c0d187c253a9d20ca406f2a2ae1ff1ea51ae43e62a4026e54cbe1e4618faf282d42fab3256e66bd6247096a68d71acc4f51a71

test:
  secret_key_base: 679092091754e28d4a6cb127f92b5ff42c1c493e89e2edeacc5f2af8285a630dfc7757f883aa6abc424a25e33bdb6dbd83a259fa2c0372057e20002340e8c947

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
